module "fortios_system_interface" {
  source = "../modules/fortios_system_interface"

  # ac_name - (optional) is a type of string
  ac_name = null
  # aggregate - (optional) is a type of string
  aggregate = null
  # algorithm - (optional) is a type of string
  algorithm = null
  # alias - (optional) is a type of string
  alias = null
  # allowaccess - (optional) is a type of string
  allowaccess = null
  # ap_discover - (optional) is a type of string
  ap_discover = null
  # arpforward - (optional) is a type of string
  arpforward = null
  # auth_type - (optional) is a type of string
  auth_type = null
  # auto_auth_extension_device - (optional) is a type of string
  auto_auth_extension_device = null
  # autogenerated - (optional) is a type of string
  autogenerated = null
  # bandwidth_measure_time - (optional) is a type of number
  bandwidth_measure_time = null
  # bfd - (optional) is a type of string
  bfd = null
  # bfd_desired_min_tx - (optional) is a type of number
  bfd_desired_min_tx = null
  # bfd_detect_mult - (optional) is a type of number
  bfd_detect_mult = null
  # bfd_required_min_rx - (optional) is a type of number
  bfd_required_min_rx = null
  # broadcast_forticlient_discovery - (optional) is a type of string
  broadcast_forticlient_discovery = null
  # broadcast_forward - (optional) is a type of string
  broadcast_forward = null
  # captive_portal - (optional) is a type of number
  captive_portal = null
  # cli_conn_status - (optional) is a type of number
  cli_conn_status = null
  # color - (optional) is a type of number
  color = null
  # dedicated_to - (optional) is a type of string
  dedicated_to = null
  # defaultgw - (optional) is a type of string
  defaultgw = null
  # description - (optional) is a type of string
  description = null
  # detected_peer_mtu - (optional) is a type of number
  detected_peer_mtu = null
  # detectprotocol - (optional) is a type of string
  detectprotocol = null
  # detectserver - (optional) is a type of string
  detectserver = null
  # device_access_list - (optional) is a type of string
  device_access_list = null
  # device_identification - (optional) is a type of string
  device_identification = null
  # device_identification_active_scan - (optional) is a type of string
  device_identification_active_scan = null
  # device_netscan - (optional) is a type of string
  device_netscan = null
  # device_user_identification - (optional) is a type of string
  device_user_identification = null
  # devindex - (optional) is a type of number
  devindex = null
  # dhcp_client_identifier - (optional) is a type of string
  dhcp_client_identifier = null
  # dhcp_relay_agent_option - (optional) is a type of string
  dhcp_relay_agent_option = null
  # dhcp_relay_interface - (optional) is a type of string
  dhcp_relay_interface = null
  # dhcp_relay_interface_select_method - (optional) is a type of string
  dhcp_relay_interface_select_method = null
  # dhcp_relay_ip - (optional) is a type of string
  dhcp_relay_ip = null
  # dhcp_relay_service - (optional) is a type of string
  dhcp_relay_service = null
  # dhcp_relay_type - (optional) is a type of string
  dhcp_relay_type = null
  # dhcp_renew_time - (optional) is a type of number
  dhcp_renew_time = null
  # disc_retry_timeout - (optional) is a type of number
  disc_retry_timeout = null
  # disconnect_threshold - (optional) is a type of number
  disconnect_threshold = null
  # distance - (optional) is a type of number
  distance = null
  # dns_server_override - (optional) is a type of string
  dns_server_override = null
  # drop_fragment - (optional) is a type of string
  drop_fragment = null
  # drop_overlapped_fragment - (optional) is a type of string
  drop_overlapped_fragment = null
  # dynamic_sort_subtable - (optional) is a type of string
  dynamic_sort_subtable = null
  # egress_shaping_profile - (optional) is a type of string
  egress_shaping_profile = null
  # endpoint_compliance - (optional) is a type of string
  endpoint_compliance = null
  # estimated_downstream_bandwidth - (optional) is a type of number
  estimated_downstream_bandwidth = null
  # estimated_upstream_bandwidth - (optional) is a type of number
  estimated_upstream_bandwidth = null
  # explicit_ftp_proxy - (optional) is a type of string
  explicit_ftp_proxy = null
  # explicit_web_proxy - (optional) is a type of string
  explicit_web_proxy = null
  # external - (optional) is a type of string
  external = null
  # fail_action_on_extender - (optional) is a type of string
  fail_action_on_extender = null
  # fail_alert_method - (optional) is a type of string
  fail_alert_method = null
  # fail_detect - (optional) is a type of string
  fail_detect = null
  # fail_detect_option - (optional) is a type of string
  fail_detect_option = null
  # fortiheartbeat - (optional) is a type of string
  fortiheartbeat = null
  # fortilink - (optional) is a type of string
  fortilink = null
  # fortilink_backup_link - (optional) is a type of number
  fortilink_backup_link = null
  # fortilink_neighbor_detect - (optional) is a type of string
  fortilink_neighbor_detect = null
  # fortilink_split_interface - (optional) is a type of string
  fortilink_split_interface = null
  # fortilink_stacking - (optional) is a type of string
  fortilink_stacking = null
  # forward_domain - (optional) is a type of number
  forward_domain = null
  # gwdetect - (optional) is a type of string
  gwdetect = null
  # ha_priority - (optional) is a type of number
  ha_priority = null
  # icmp_accept_redirect - (optional) is a type of string
  icmp_accept_redirect = null
  # icmp_send_redirect - (optional) is a type of string
  icmp_send_redirect = null
  # ident_accept - (optional) is a type of string
  ident_accept = null
  # idle_timeout - (optional) is a type of number
  idle_timeout = null
  # inbandwidth - (optional) is a type of number
  inbandwidth = null
  # ingress_shaping_profile - (optional) is a type of string
  ingress_shaping_profile = null
  # ingress_spillover_threshold - (optional) is a type of number
  ingress_spillover_threshold = null
  # interface - (optional) is a type of string
  interface = null
  # internal - (optional) is a type of number
  internal = null
  # ip - (optional) is a type of string
  ip = null
  # ip_managed_by_fortiipam - (optional) is a type of string
  ip_managed_by_fortiipam = null
  # ipmac - (optional) is a type of string
  ipmac = null
  # ips_sniffer_mode - (optional) is a type of string
  ips_sniffer_mode = null
  # ipunnumbered - (optional) is a type of string
  ipunnumbered = null
  # l2forward - (optional) is a type of string
  l2forward = null
  # lacp_ha_slave - (optional) is a type of string
  lacp_ha_slave = null
  # lacp_mode - (optional) is a type of string
  lacp_mode = null
  # lacp_speed - (optional) is a type of string
  lacp_speed = null
  # lcp_echo_interval - (optional) is a type of number
  lcp_echo_interval = null
  # lcp_max_echo_fails - (optional) is a type of number
  lcp_max_echo_fails = null
  # link_up_delay - (optional) is a type of number
  link_up_delay = null
  # lldp_network_policy - (optional) is a type of string
  lldp_network_policy = null
  # lldp_reception - (optional) is a type of string
  lldp_reception = null
  # lldp_transmission - (optional) is a type of string
  lldp_transmission = null
  # macaddr - (optional) is a type of string
  macaddr = null
  # managed_subnetwork_size - (optional) is a type of string
  managed_subnetwork_size = null
  # management_ip - (optional) is a type of string
  management_ip = null
  # measured_downstream_bandwidth - (optional) is a type of number
  measured_downstream_bandwidth = null
  # measured_upstream_bandwidth - (optional) is a type of number
  measured_upstream_bandwidth = null
  # min_links - (optional) is a type of number
  min_links = null
  # min_links_down - (optional) is a type of string
  min_links_down = null
  # mode - (optional) is a type of string
  mode = null
  # monitor_bandwidth - (optional) is a type of string
  monitor_bandwidth = null
  # mtu - (optional) is a type of number
  mtu = null
  # mtu_override - (optional) is a type of string
  mtu_override = null
  # name - (required) is a type of string
  name = null
  # ndiscforward - (optional) is a type of string
  ndiscforward = null
  # netbios_forward - (optional) is a type of string
  netbios_forward = null
  # netflow_sampler - (optional) is a type of string
  netflow_sampler = null
  # outbandwidth - (optional) is a type of number
  outbandwidth = null
  # padt_retry_timeout - (optional) is a type of number
  padt_retry_timeout = null
  # password - (optional) is a type of string
  password = null
  # ping_serv_status - (optional) is a type of number
  ping_serv_status = null
  # polling_interval - (optional) is a type of number
  polling_interval = null
  # pppoe_unnumbered_negotiate - (optional) is a type of string
  pppoe_unnumbered_negotiate = null
  # pptp_auth_type - (optional) is a type of string
  pptp_auth_type = null
  # pptp_client - (optional) is a type of string
  pptp_client = null
  # pptp_password - (optional) is a type of string
  pptp_password = null
  # pptp_server_ip - (optional) is a type of string
  pptp_server_ip = null
  # pptp_timeout - (optional) is a type of number
  pptp_timeout = null
  # pptp_user - (optional) is a type of string
  pptp_user = null
  # preserve_session_route - (optional) is a type of string
  preserve_session_route = null
  # priority - (optional) is a type of number
  priority = null
  # priority_override - (optional) is a type of string
  priority_override = null
  # proxy_captive_portal - (optional) is a type of string
  proxy_captive_portal = null
  # redundant_interface - (optional) is a type of string
  redundant_interface = null
  # remote_ip - (optional) is a type of string
  remote_ip = null
  # replacemsg_override_group - (optional) is a type of string
  replacemsg_override_group = null
  # ring_rx - (optional) is a type of number
  ring_rx = null
  # ring_tx - (optional) is a type of number
  ring_tx = null
  # role - (optional) is a type of string
  role = null
  # sample_direction - (optional) is a type of string
  sample_direction = null
  # sample_rate - (optional) is a type of number
  sample_rate = null
  # scan_botnet_connections - (optional) is a type of string
  scan_botnet_connections = null
  # secondary_ip - (optional) is a type of string
  secondary_ip = null
  # security_exempt_list - (optional) is a type of string
  security_exempt_list = null
  # security_external_logout - (optional) is a type of string
  security_external_logout = null
  # security_external_web - (optional) is a type of string
  security_external_web = null
  # security_mac_auth_bypass - (optional) is a type of string
  security_mac_auth_bypass = null
  # security_mode - (optional) is a type of string
  security_mode = null
  # security_redirect_url - (optional) is a type of string
  security_redirect_url = null
  # service_name - (optional) is a type of string
  service_name = null
  # sflow_sampler - (optional) is a type of string
  sflow_sampler = null
  # snmp_index - (optional) is a type of number
  snmp_index = null
  # speed - (optional) is a type of string
  speed = null
  # spillover_threshold - (optional) is a type of number
  spillover_threshold = null
  # src_check - (optional) is a type of string
  src_check = null
  # status - (optional) is a type of string
  status = null
  # stpforward - (optional) is a type of string
  stpforward = null
  # stpforward_mode - (optional) is a type of string
  stpforward_mode = null
  # subst - (optional) is a type of string
  subst = null
  # substitute_dst_mac - (optional) is a type of string
  substitute_dst_mac = null
  # swc_first_create - (optional) is a type of number
  swc_first_create = null
  # swc_vlan - (optional) is a type of number
  swc_vlan = null
  # switch - (optional) is a type of string
  switch = null
  # switch_controller_access_vlan - (optional) is a type of string
  switch_controller_access_vlan = null
  # switch_controller_arp_inspection - (optional) is a type of string
  switch_controller_arp_inspection = null
  # switch_controller_dhcp_snooping - (optional) is a type of string
  switch_controller_dhcp_snooping = null
  # switch_controller_dhcp_snooping_option82 - (optional) is a type of string
  switch_controller_dhcp_snooping_option82 = null
  # switch_controller_dhcp_snooping_verify_mac - (optional) is a type of string
  switch_controller_dhcp_snooping_verify_mac = null
  # switch_controller_feature - (optional) is a type of string
  switch_controller_feature = null
  # switch_controller_igmp_snooping - (optional) is a type of string
  switch_controller_igmp_snooping = null
  # switch_controller_igmp_snooping_fast_leave - (optional) is a type of string
  switch_controller_igmp_snooping_fast_leave = null
  # switch_controller_igmp_snooping_proxy - (optional) is a type of string
  switch_controller_igmp_snooping_proxy = null
  # switch_controller_iot_scanning - (optional) is a type of string
  switch_controller_iot_scanning = null
  # switch_controller_learning_limit - (optional) is a type of number
  switch_controller_learning_limit = null
  # switch_controller_mgmt_vlan - (optional) is a type of number
  switch_controller_mgmt_vlan = null
  # switch_controller_nac - (optional) is a type of string
  switch_controller_nac = null
  # switch_controller_rspan_mode - (optional) is a type of string
  switch_controller_rspan_mode = null
  # switch_controller_source_ip - (optional) is a type of string
  switch_controller_source_ip = null
  # switch_controller_traffic_policy - (optional) is a type of string
  switch_controller_traffic_policy = null
  # tcp_mss - (optional) is a type of number
  tcp_mss = null
  # trust_ip6_1 - (optional) is a type of string
  trust_ip6_1 = null
  # trust_ip6_2 - (optional) is a type of string
  trust_ip6_2 = null
  # trust_ip6_3 - (optional) is a type of string
  trust_ip6_3 = null
  # trust_ip_1 - (optional) is a type of string
  trust_ip_1 = null
  # trust_ip_2 - (optional) is a type of string
  trust_ip_2 = null
  # trust_ip_3 - (optional) is a type of string
  trust_ip_3 = null
  # type - (optional) is a type of string
  type = null
  # username - (optional) is a type of string
  username = null
  # vdom - (required) is a type of string
  vdom = null
  # vindex - (optional) is a type of number
  vindex = null
  # vlan_protocol - (optional) is a type of string
  vlan_protocol = null
  # vlanforward - (optional) is a type of string
  vlanforward = null
  # vlanid - (optional) is a type of number
  vlanid = null
  # vrf - (optional) is a type of number
  vrf = null
  # vrrp_virtual_mac - (optional) is a type of string
  vrrp_virtual_mac = null
  # wccp - (optional) is a type of string
  wccp = null
  # weight - (optional) is a type of number
  weight = null
  # wins_ip - (optional) is a type of string
  wins_ip = null

  client_options = [{
    code  = null
    id    = null
    ip    = null
    type  = null
    value = null
  }]

  fail_alert_interfaces = [{
    name = null
  }]

  ipv6 = [{
    autoconf                  = null
    cli_conn6_status          = null
    dhcp6_client_options      = null
    dhcp6_information_request = null
    dhcp6_prefix_delegation   = null
    dhcp6_prefix_hint         = null
    dhcp6_prefix_hint_plt     = null
    dhcp6_prefix_hint_vlt     = null
    dhcp6_relay_ip            = null
    dhcp6_relay_service       = null
    dhcp6_relay_type          = null
    icmp6_send_redirect       = null
    interface_identifier      = null
    ip6_address               = null
    ip6_allowaccess           = null
    ip6_default_life          = null
    ip6_delegated_prefix_list = [{
      autonomous_flag    = null
      onlink_flag        = null
      prefix_id          = null
      rdnss              = null
      rdnss_service      = null
      subnet             = null
      upstream_interface = null
    }]
    ip6_dns_server_override = null
    ip6_extra_addr = [{
      prefix = null
    }]
    ip6_hop_limit    = null
    ip6_link_mtu     = null
    ip6_manage_flag  = null
    ip6_max_interval = null
    ip6_min_interval = null
    ip6_mode         = null
    ip6_other_flag   = null
    ip6_prefix_list = [{
      autonomous_flag = null
      dnssl = [{
        domain = null
      }]
      onlink_flag         = null
      preferred_life_time = null
      prefix              = null
      rdnss               = null
      valid_life_time     = null
    }]
    ip6_prefix_mode        = null
    ip6_reachable_time     = null
    ip6_retrans_time       = null
    ip6_send_adv           = null
    ip6_subnet             = null
    ip6_upstream_interface = null
    nd_cert                = null
    nd_cga_modifier        = null
    nd_mode                = null
    nd_security_level      = null
    nd_timestamp_delta     = null
    nd_timestamp_fuzz      = null
    unique_autoconf_addr   = null
    vrip6_link_local       = null
    vrrp6 = [{
      accept_mode  = null
      adv_interval = null
      preempt      = null
      priority     = null
      start_time   = null
      status       = null
      vrdst6       = null
      vrgrp        = null
      vrid         = null
      vrip6        = null
    }]
    vrrp_virtual_mac6 = null
  }]

  managed_device = [{
    name = null
  }]

  member = [{
    interface_name = null
  }]

  secondaryip = [{
    allowaccess      = null
    detectprotocol   = null
    detectserver     = null
    gwdetect         = null
    ha_priority      = null
    id               = null
    ip               = null
    ping_serv_status = null
  }]

  security_groups = [{
    name = null
  }]

  tagging = [{
    category = null
    name     = null
    tags = [{
      name = null
    }]
  }]

  vrrp = [{
    accept_mode          = null
    adv_interval         = null
    ignore_default_route = null
    preempt              = null
    priority             = null
    proxy_arp = [{
      id = null
      ip = null
    }]
    start_time     = null
    status         = null
    version        = null
    vrdst          = null
    vrdst_priority = null
    vrgrp          = null
    vrid           = null
    vrip           = null
  }]
}