variable "ac_name" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "aggregate" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "algorithm" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "alias" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "allowaccess" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "ap_discover" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "arpforward" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "auth_type" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "auto_auth_extension_device" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "autogenerated" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "bandwidth_measure_time" {
  description = "(optional)"
  type        = number
  default     = null
}

variable "bfd" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "bfd_desired_min_tx" {
  description = "(optional)"
  type        = number
  default     = null
}

variable "bfd_detect_mult" {
  description = "(optional)"
  type        = number
  default     = null
}

variable "bfd_required_min_rx" {
  description = "(optional)"
  type        = number
  default     = null
}

variable "broadcast_forticlient_discovery" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "broadcast_forward" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "captive_portal" {
  description = "(optional)"
  type        = number
  default     = null
}

variable "cli_conn_status" {
  description = "(optional)"
  type        = number
  default     = null
}

variable "color" {
  description = "(optional)"
  type        = number
  default     = null
}

variable "dedicated_to" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "defaultgw" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "description" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "detected_peer_mtu" {
  description = "(optional)"
  type        = number
  default     = null
}

variable "detectprotocol" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "detectserver" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "device_access_list" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "device_identification" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "device_identification_active_scan" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "device_netscan" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "device_user_identification" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "devindex" {
  description = "(optional)"
  type        = number
  default     = null
}

variable "dhcp_client_identifier" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "dhcp_relay_agent_option" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "dhcp_relay_interface" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "dhcp_relay_interface_select_method" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "dhcp_relay_ip" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "dhcp_relay_service" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "dhcp_relay_type" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "dhcp_renew_time" {
  description = "(optional)"
  type        = number
  default     = null
}

variable "disc_retry_timeout" {
  description = "(optional)"
  type        = number
  default     = null
}

variable "disconnect_threshold" {
  description = "(optional)"
  type        = number
  default     = null
}

variable "distance" {
  description = "(optional)"
  type        = number
  default     = null
}

variable "dns_server_override" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "drop_fragment" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "drop_overlapped_fragment" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "dynamic_sort_subtable" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "egress_shaping_profile" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "endpoint_compliance" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "estimated_downstream_bandwidth" {
  description = "(optional)"
  type        = number
  default     = null
}

variable "estimated_upstream_bandwidth" {
  description = "(optional)"
  type        = number
  default     = null
}

variable "explicit_ftp_proxy" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "explicit_web_proxy" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "external" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "fail_action_on_extender" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "fail_alert_method" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "fail_detect" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "fail_detect_option" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "fortiheartbeat" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "fortilink" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "fortilink_backup_link" {
  description = "(optional)"
  type        = number
  default     = null
}

variable "fortilink_neighbor_detect" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "fortilink_split_interface" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "fortilink_stacking" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "forward_domain" {
  description = "(optional)"
  type        = number
  default     = null
}

variable "gwdetect" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "ha_priority" {
  description = "(optional)"
  type        = number
  default     = null
}

variable "icmp_accept_redirect" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "icmp_send_redirect" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "ident_accept" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "idle_timeout" {
  description = "(optional)"
  type        = number
  default     = null
}

variable "inbandwidth" {
  description = "(optional)"
  type        = number
  default     = null
}

variable "ingress_shaping_profile" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "ingress_spillover_threshold" {
  description = "(optional)"
  type        = number
  default     = null
}

variable "interface" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "internal" {
  description = "(optional)"
  type        = number
  default     = null
}

variable "ip" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "ip_managed_by_fortiipam" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "ipmac" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "ips_sniffer_mode" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "ipunnumbered" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "l2forward" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "lacp_ha_slave" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "lacp_mode" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "lacp_speed" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "lcp_echo_interval" {
  description = "(optional)"
  type        = number
  default     = null
}

variable "lcp_max_echo_fails" {
  description = "(optional)"
  type        = number
  default     = null
}

variable "link_up_delay" {
  description = "(optional)"
  type        = number
  default     = null
}

variable "lldp_network_policy" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "lldp_reception" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "lldp_transmission" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "macaddr" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "managed_subnetwork_size" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "management_ip" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "measured_downstream_bandwidth" {
  description = "(optional)"
  type        = number
  default     = null
}

variable "measured_upstream_bandwidth" {
  description = "(optional)"
  type        = number
  default     = null
}

variable "min_links" {
  description = "(optional)"
  type        = number
  default     = null
}

variable "min_links_down" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "mode" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "monitor_bandwidth" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "mtu" {
  description = "(optional)"
  type        = number
  default     = null
}

variable "mtu_override" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "name" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "ndiscforward" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "netbios_forward" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "netflow_sampler" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "outbandwidth" {
  description = "(optional)"
  type        = number
  default     = null
}

variable "padt_retry_timeout" {
  description = "(optional)"
  type        = number
  default     = null
}

variable "password" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "ping_serv_status" {
  description = "(optional)"
  type        = number
  default     = null
}

variable "polling_interval" {
  description = "(optional)"
  type        = number
  default     = null
}

variable "pppoe_unnumbered_negotiate" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "pptp_auth_type" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "pptp_client" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "pptp_password" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "pptp_server_ip" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "pptp_timeout" {
  description = "(optional)"
  type        = number
  default     = null
}

variable "pptp_user" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "preserve_session_route" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "priority" {
  description = "(optional)"
  type        = number
  default     = null
}

variable "priority_override" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "proxy_captive_portal" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "redundant_interface" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "remote_ip" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "replacemsg_override_group" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "ring_rx" {
  description = "(optional)"
  type        = number
  default     = null
}

variable "ring_tx" {
  description = "(optional)"
  type        = number
  default     = null
}

variable "role" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "sample_direction" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "sample_rate" {
  description = "(optional)"
  type        = number
  default     = null
}

variable "scan_botnet_connections" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "secondary_ip" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "security_exempt_list" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "security_external_logout" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "security_external_web" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "security_mac_auth_bypass" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "security_mode" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "security_redirect_url" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "service_name" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "sflow_sampler" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "snmp_index" {
  description = "(optional)"
  type        = number
  default     = null
}

variable "speed" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "spillover_threshold" {
  description = "(optional)"
  type        = number
  default     = null
}

variable "src_check" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "status" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "stpforward" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "stpforward_mode" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "subst" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "substitute_dst_mac" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "swc_first_create" {
  description = "(optional)"
  type        = number
  default     = null
}

variable "swc_vlan" {
  description = "(optional)"
  type        = number
  default     = null
}

variable "switch" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "switch_controller_access_vlan" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "switch_controller_arp_inspection" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "switch_controller_dhcp_snooping" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "switch_controller_dhcp_snooping_option82" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "switch_controller_dhcp_snooping_verify_mac" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "switch_controller_feature" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "switch_controller_igmp_snooping" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "switch_controller_igmp_snooping_fast_leave" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "switch_controller_igmp_snooping_proxy" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "switch_controller_iot_scanning" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "switch_controller_learning_limit" {
  description = "(optional)"
  type        = number
  default     = null
}

variable "switch_controller_mgmt_vlan" {
  description = "(optional)"
  type        = number
  default     = null
}

variable "switch_controller_nac" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "switch_controller_rspan_mode" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "switch_controller_source_ip" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "switch_controller_traffic_policy" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "tcp_mss" {
  description = "(optional)"
  type        = number
  default     = null
}

variable "trust_ip6_1" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "trust_ip6_2" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "trust_ip6_3" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "trust_ip_1" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "trust_ip_2" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "trust_ip_3" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "type" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "username" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "vdom" {
  description = "(required)"
  type        = string
}

variable "vindex" {
  description = "(optional)"
  type        = number
  default     = null
}

variable "vlan_protocol" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "vlanforward" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "vlanid" {
  description = "(optional)"
  type        = number
  default     = null
}

variable "vrf" {
  description = "(optional)"
  type        = number
  default     = null
}

variable "vrrp_virtual_mac" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "wccp" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "weight" {
  description = "(optional)"
  type        = number
  default     = null
}

variable "wins_ip" {
  description = "(optional)"
  type        = string
  default     = null
}

variable "client_options" {
  description = "nested block: NestingList, min items: 0, max items: 0"
  type = set(object(
    {
      code  = number
      id    = number
      ip    = string
      type  = string
      value = string
    }
  ))
  default = []
}

variable "fail_alert_interfaces" {
  description = "nested block: NestingList, min items: 0, max items: 0"
  type = set(object(
    {
      name = string
    }
  ))
  default = []
}

variable "ipv6" {
  description = "nested block: NestingList, min items: 0, max items: 1"
  type = set(object(
    {
      autoconf                  = string
      cli_conn6_status          = number
      dhcp6_client_options      = string
      dhcp6_information_request = string
      dhcp6_prefix_delegation   = string
      dhcp6_prefix_hint         = string
      dhcp6_prefix_hint_plt     = number
      dhcp6_prefix_hint_vlt     = number
      dhcp6_relay_ip            = string
      dhcp6_relay_service       = string
      dhcp6_relay_type          = string
      icmp6_send_redirect       = string
      interface_identifier      = string
      ip6_address               = string
      ip6_allowaccess           = string
      ip6_default_life          = number
      ip6_delegated_prefix_list = list(object(
        {
          autonomous_flag    = string
          onlink_flag        = string
          prefix_id          = number
          rdnss              = string
          rdnss_service      = string
          subnet             = string
          upstream_interface = string
        }
      ))
      ip6_dns_server_override = string
      ip6_extra_addr = list(object(
        {
          prefix = string
        }
      ))
      ip6_hop_limit    = number
      ip6_link_mtu     = number
      ip6_manage_flag  = string
      ip6_max_interval = number
      ip6_min_interval = number
      ip6_mode         = string
      ip6_other_flag   = string
      ip6_prefix_list = list(object(
        {
          autonomous_flag = string
          dnssl = list(object(
            {
              domain = string
            }
          ))
          onlink_flag         = string
          preferred_life_time = number
          prefix              = string
          rdnss               = string
          valid_life_time     = number
        }
      ))
      ip6_prefix_mode        = string
      ip6_reachable_time     = number
      ip6_retrans_time       = number
      ip6_send_adv           = string
      ip6_subnet             = string
      ip6_upstream_interface = string
      nd_cert                = string
      nd_cga_modifier        = string
      nd_mode                = string
      nd_security_level      = number
      nd_timestamp_delta     = number
      nd_timestamp_fuzz      = number
      unique_autoconf_addr   = string
      vrip6_link_local       = string
      vrrp6 = list(object(
        {
          accept_mode  = string
          adv_interval = number
          preempt      = string
          priority     = number
          start_time   = number
          status       = string
          vrdst6       = string
          vrgrp        = number
          vrid         = number
          vrip6        = string
        }
      ))
      vrrp_virtual_mac6 = string
    }
  ))
  default = []
}

variable "managed_device" {
  description = "nested block: NestingList, min items: 0, max items: 0"
  type = set(object(
    {
      name = string
    }
  ))
  default = []
}

variable "member" {
  description = "nested block: NestingList, min items: 0, max items: 0"
  type = set(object(
    {
      interface_name = string
    }
  ))
  default = []
}

variable "secondaryip" {
  description = "nested block: NestingList, min items: 0, max items: 0"
  type = set(object(
    {
      allowaccess      = string
      detectprotocol   = string
      detectserver     = string
      gwdetect         = string
      ha_priority      = number
      id               = number
      ip               = string
      ping_serv_status = number
    }
  ))
  default = []
}

variable "security_groups" {
  description = "nested block: NestingList, min items: 0, max items: 0"
  type = set(object(
    {
      name = string
    }
  ))
  default = []
}

variable "tagging" {
  description = "nested block: NestingList, min items: 0, max items: 0"
  type = set(object(
    {
      category = string
      name     = string
      tags = list(object(
        {
          name = string
        }
      ))
    }
  ))
  default = []
}

variable "vrrp" {
  description = "nested block: NestingList, min items: 0, max items: 0"
  type = set(object(
    {
      accept_mode          = string
      adv_interval         = number
      ignore_default_route = string
      preempt              = string
      priority             = number
      proxy_arp = list(object(
        {
          id = number
          ip = string
        }
      ))
      start_time     = number
      status         = string
      version        = string
      vrdst          = string
      vrdst_priority = number
      vrgrp          = number
      vrid           = number
      vrip           = string
    }
  ))
  default = []
}